### ISSUE TITLE
Error sending new user registration email confirmation.

### ISSUE THREAD

**Issue by jmg1138** [nothingworksright/api.recipe.report#61]
[api-recipe-report] [2021-10-31 05:21:54] main[root] (INFO) Request: POST /user/register
[api-recipe-report] [2021-10-31 05:21:59] main[root] (WARN) A pg client has been out for more than 5 seconds!
[api-recipe-report] [2021-10-31 05:26:09] main[root] (ERROR) Sendmail error: Error name: Error. Error message: can not connect to any SMTP server Error: can not connect to any SMTP server
[api-recipe-report] [2021-10-31 05:26:09]     at tryConnect (/workspace/node_modules/sendmail/sendmail.js:88:49)
[api-recipe-report] [2021-10-31 05:26:09]     at Socket.<anonymous> (/workspace/node_modules/sendmail/sendmail.js:94:13)
[api-recipe-report] [2021-10-31 05:26:09]     at Socket.emit (events.js:400:28)
[api-recipe-report] [2021-10-31 05:26:09]     at emitErrorNT (internal/streams/destroy.js:106:8)
[api-recipe-report] [2021-10-31 05:26:09]     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
[api-recipe-report] [2021-10-31 05:26:09]     at processTicksAndRejections (internal/process/task_queues.js:82:21)
[api-recipe-report] [2021-10-31 05:26:09] main[root] (ERROR) can not connect to any SMTP server
[api-recipe-report] [2021-10-31 05:26:09] main[root] (ERROR) Responder|Error|200|Error registering user: can not connect to any SMTP server

**Comment by jmg1138** [comment]
The real solution to this problem is to enhance the `email-message-service` so that it no longer uses sendmail, and instead uses a real transactional email service.  

To start, I think we will try [mailersend](https://www.mailersend.com/pricing).
